### ISSUE TITLE
Figure out and document how to hook up components in WP

### ISSUE THREAD

**Issue by oxyc** [generoi/genero-design-system#12]
- Polyfills only on old browsers
- Can we use `<script type="module">` on modern on what?
- What happens with webpack and lazy loading etc?

**Comment by silentnoodlemaster** [comment]
adapted from the stencil documentation and tested in sage:

```js
import { applyPolyfills, defineCustomElements } from 'genero-design-system/loader';

applyPolyfills().then(() => {
  defineCustomElements();
});
```

**Comment by oxyc** [comment]
Could you add this together with react usage to the readme?
