### ISSUE TITLE
MasonryGrid

### ISSUE THREAD

**Issue by oxyc** [generoi/genero-design-system#48]
Skip columns implantation and rely on JS. Too many bugs with css columns and layering

**Comment by taromorimoto** [comment]
Yeah, it might be fine to do this with JS. Also usually the masonry grid is anyways below the fold so it can have time to load.

**Comment by taromorimoto** [comment]
Yeah, it might be fine to do this with JS. Also usually the masonry grid is anyways below the fold so it can have time to load.

**Comment by oxyc** [comment]
Deleted a duplicate :)

Something like this https://codepen.io/andybarefoot/pen/QMeZda
https://medium.com/@andybarefoot/a-masonry-style-layout-using-css-grid-8c663d355ebb
