### ISSUE TITLE
Prefix css variables with `--gds-` or not?

### ISSUE THREAD

**Issue by taromorimoto** [generoi/genero-design-system#50]
In general since we are now making a lot of breaking changes (increment major version) I think it would make sense to also prefix all the css variables with "gds" (e.g. --gds-menu-item-underline-display).

**Comment by oxyc** [comment]
https://github.com/generoi/genero-design-system/pull/51/commits/e2574652a7a4a07b74711b1dd579ba85c44e19f1

Fixed for the menu here and I provided upgrade path from the previous variables.

**Comment by oxyc** [comment]
Maybe we should skip including that deprecation file as a default but include it to help sites transition?

At the same time I feel like we need to rename the sizing variables to use numbers. `spacing-xxxxxl` really doesn't work :D 

https://github.com/generoi/tehdas/blob/870bb117929b079c9f347f670d7aea16abada74c/web/app/themes/wp-gds-theme/resources/assets/styles/config/variables.scss#L34:L36

**Comment by oxyc** [comment]
did some sed and vim macro magic for the rest https://github.com/generoi/genero-design-system/pull/52 so that PR tracks this issue now.

**Comment by taromorimoto** [comment]
I like the deprecations file, and like you say, it's probably good to include it as an optional helper if a site chooses to use it or not.

**Comment by taromorimoto** [comment]
I understand the spacing-xxxxl issue and maybe I was wrong trying to push it in the beginning of the project. 😊 So maybe that sed magic could also fix this? :)
